#!/bin/sh
#
# init.d script for MirrorBot Daemon
#
# chkconfig: 345 81 20
# description: MirrorBot Daemon

### BEGIN INIT INFO
# Provides:          mirrorbotd
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop mirrorbot server
### END INIT INFO

/opt/mirrorbot/bin/mirrorbotctl.sh $1
